//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2500
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace is2AdminClient {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class 送り状データ : DataSet {
        
        private table送り状DataTable tabletable送り状;
        
        public 送り状データ() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected 送り状データ(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["table送り状"] != null)) {
                    this.Tables.Add(new table送り状DataTable(ds.Tables["table送り状"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public table送り状DataTable table送り状 {
            get {
                return this.tabletable送り状;
            }
        }
        
        public override DataSet Clone() {
            送り状データ cln = ((送り状データ)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["table送り状"] != null)) {
                this.Tables.Add(new table送り状DataTable(ds.Tables["table送り状"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tabletable送り状 = ((table送り状DataTable)(this.Tables["table送り状"]));
            if ((this.tabletable送り状 != null)) {
                this.tabletable送り状.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "送り状データ";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/送り状データ.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tabletable送り状 = new table送り状DataTable();
            this.Tables.Add(this.tabletable送り状);
        }
        
        private bool ShouldSerializetable送り状() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void table送り状RowChangeEventHandler(object sender, table送り状RowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class table送り状DataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn column荷受人ＣＤ;
            
            private DataColumn column荷受人電話番号;
            
            private DataColumn column荷受人住所県;
            
            private DataColumn column荷受人住所市;
            
            private DataColumn column荷受人住所町;
            
            private DataColumn column荷受人住所１;
            
            private DataColumn column荷受人住所２;
            
            private DataColumn column荷受人住所３;
            
            private DataColumn column荷受人名前１;
            
            private DataColumn column荷受人名前２;
            
            private DataColumn column荷受人名前３;
            
            private DataColumn column出荷日年;
            
            private DataColumn column出荷日月;
            
            private DataColumn column出荷日日;
            
            private DataColumn column送り状番号;
            
            private DataColumn columnバーコード;
            
            private DataColumn column着店ＣＤ;
            
            private DataColumn column発店ＣＤ;
            
            private DataColumn column荷送人電話番号;
            
            private DataColumn column荷送人住所１;
            
            private DataColumn column荷送人住所２;
            
            private DataColumn column荷送人住所３;
            
            private DataColumn column荷送人名前１;
            
            private DataColumn column荷送人名前２;
            
            private DataColumn column担当者;
            
            private DataColumn column個数;
            
            private DataColumn column連番;
            
            private DataColumn column重量;
            
            private DataColumn column保険料;
            
            private DataColumn column指定日;
            
            private DataColumn columnお客様番号;
            
            private DataColumn column輸送記事１;
            
            private DataColumn column輸送記事２;
            
            private DataColumn column品名記事１;
            
            private DataColumn column品名記事２;
            
            private DataColumn column品名記事３;
            
            private DataColumn column品名記事４;
            
            private DataColumn column品名記事５;
            
            private DataColumn column品名記事６;
            
            private DataColumn column印刷順;
            
            private DataColumn column仕分ＣＤ;
            
            private DataColumn column発店名;
            
            private DataColumn column荷受人フォントサイズ拡大FLG;
            
            private DataColumn column荷受人郵便番号;
            
            private DataColumn column荷送人郵便番号;
            
            private DataColumn column王子運送FLG;
            
            private DataColumn column重量入力制御;
            
            private DataColumn column着店名;
            
            internal table送り状DataTable() : 
                    base("table送り状") {
                this.InitClass();
            }
            
            internal table送り状DataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn 荷受人ＣＤColumn {
                get {
                    return this.column荷受人ＣＤ;
                }
            }
            
            internal DataColumn 荷受人電話番号Column {
                get {
                    return this.column荷受人電話番号;
                }
            }
            
            internal DataColumn 荷受人住所県Column {
                get {
                    return this.column荷受人住所県;
                }
            }
            
            internal DataColumn 荷受人住所市Column {
                get {
                    return this.column荷受人住所市;
                }
            }
            
            internal DataColumn 荷受人住所町Column {
                get {
                    return this.column荷受人住所町;
                }
            }
            
            internal DataColumn 荷受人住所１Column {
                get {
                    return this.column荷受人住所１;
                }
            }
            
            internal DataColumn 荷受人住所２Column {
                get {
                    return this.column荷受人住所２;
                }
            }
            
            internal DataColumn 荷受人住所３Column {
                get {
                    return this.column荷受人住所３;
                }
            }
            
            internal DataColumn 荷受人名前１Column {
                get {
                    return this.column荷受人名前１;
                }
            }
            
            internal DataColumn 荷受人名前２Column {
                get {
                    return this.column荷受人名前２;
                }
            }
            
            internal DataColumn 荷受人名前３Column {
                get {
                    return this.column荷受人名前３;
                }
            }
            
            internal DataColumn 出荷日年Column {
                get {
                    return this.column出荷日年;
                }
            }
            
            internal DataColumn 出荷日月Column {
                get {
                    return this.column出荷日月;
                }
            }
            
            internal DataColumn 出荷日日Column {
                get {
                    return this.column出荷日日;
                }
            }
            
            internal DataColumn 送り状番号Column {
                get {
                    return this.column送り状番号;
                }
            }
            
            internal DataColumn バーコードColumn {
                get {
                    return this.columnバーコード;
                }
            }
            
            internal DataColumn 着店ＣＤColumn {
                get {
                    return this.column着店ＣＤ;
                }
            }
            
            internal DataColumn 発店ＣＤColumn {
                get {
                    return this.column発店ＣＤ;
                }
            }
            
            internal DataColumn 荷送人電話番号Column {
                get {
                    return this.column荷送人電話番号;
                }
            }
            
            internal DataColumn 荷送人住所１Column {
                get {
                    return this.column荷送人住所１;
                }
            }
            
            internal DataColumn 荷送人住所２Column {
                get {
                    return this.column荷送人住所２;
                }
            }
            
            internal DataColumn 荷送人住所３Column {
                get {
                    return this.column荷送人住所３;
                }
            }
            
            internal DataColumn 荷送人名前１Column {
                get {
                    return this.column荷送人名前１;
                }
            }
            
            internal DataColumn 荷送人名前２Column {
                get {
                    return this.column荷送人名前２;
                }
            }
            
            internal DataColumn 担当者Column {
                get {
                    return this.column担当者;
                }
            }
            
            internal DataColumn 個数Column {
                get {
                    return this.column個数;
                }
            }
            
            internal DataColumn 連番Column {
                get {
                    return this.column連番;
                }
            }
            
            internal DataColumn 重量Column {
                get {
                    return this.column重量;
                }
            }
            
            internal DataColumn 保険料Column {
                get {
                    return this.column保険料;
                }
            }
            
            internal DataColumn 指定日Column {
                get {
                    return this.column指定日;
                }
            }
            
            internal DataColumn お客様番号Column {
                get {
                    return this.columnお客様番号;
                }
            }
            
            internal DataColumn 輸送記事１Column {
                get {
                    return this.column輸送記事１;
                }
            }
            
            internal DataColumn 輸送記事２Column {
                get {
                    return this.column輸送記事２;
                }
            }
            
            internal DataColumn 品名記事１Column {
                get {
                    return this.column品名記事１;
                }
            }
            
            internal DataColumn 品名記事２Column {
                get {
                    return this.column品名記事２;
                }
            }
            
            internal DataColumn 品名記事３Column {
                get {
                    return this.column品名記事３;
                }
            }
            
            internal DataColumn 品名記事４Column {
                get {
                    return this.column品名記事４;
                }
            }
            
            internal DataColumn 品名記事５Column {
                get {
                    return this.column品名記事５;
                }
            }
            
            internal DataColumn 品名記事６Column {
                get {
                    return this.column品名記事６;
                }
            }
            
            internal DataColumn 印刷順Column {
                get {
                    return this.column印刷順;
                }
            }
            
            internal DataColumn 仕分ＣＤColumn {
                get {
                    return this.column仕分ＣＤ;
                }
            }
            
            internal DataColumn 発店名Column {
                get {
                    return this.column発店名;
                }
            }
            
            internal DataColumn 荷受人フォントサイズ拡大FLGColumn {
                get {
                    return this.column荷受人フォントサイズ拡大FLG;
                }
            }
            
            internal DataColumn 荷受人郵便番号Column {
                get {
                    return this.column荷受人郵便番号;
                }
            }
            
            internal DataColumn 荷送人郵便番号Column {
                get {
                    return this.column荷送人郵便番号;
                }
            }
            
            internal DataColumn 王子運送FLGColumn {
                get {
                    return this.column王子運送FLG;
                }
            }
            
            internal DataColumn 重量入力制御Column {
                get {
                    return this.column重量入力制御;
                }
            }
            
            internal DataColumn 着店名Column {
                get {
                    return this.column着店名;
                }
            }
            
            public table送り状Row this[int index] {
                get {
                    return ((table送り状Row)(this.Rows[index]));
                }
            }
            
            public event table送り状RowChangeEventHandler table送り状RowChanged;
            
            public event table送り状RowChangeEventHandler table送り状RowChanging;
            
            public event table送り状RowChangeEventHandler table送り状RowDeleted;
            
            public event table送り状RowChangeEventHandler table送り状RowDeleting;
            
            public void Addtable送り状Row(table送り状Row row) {
                this.Rows.Add(row);
            }
            
            public table送り状Row Addtable送り状Row(
                        string 荷受人ＣＤ, 
                        string 荷受人電話番号, 
                        string 荷受人住所県, 
                        string 荷受人住所市, 
                        string 荷受人住所町, 
                        string 荷受人住所１, 
                        string 荷受人住所２, 
                        string 荷受人住所３, 
                        string 荷受人名前１, 
                        string 荷受人名前２, 
                        string 荷受人名前３, 
                        string 出荷日年, 
                        string 出荷日月, 
                        string 出荷日日, 
                        string 送り状番号, 
                        string バーコード, 
                        string 着店ＣＤ, 
                        string 発店ＣＤ, 
                        string 荷送人電話番号, 
                        string 荷送人住所１, 
                        string 荷送人住所２, 
                        string 荷送人住所３, 
                        string 荷送人名前１, 
                        string 荷送人名前２, 
                        string 担当者, 
                        string 個数, 
                        string 連番, 
                        string 重量, 
                        string 保険料, 
                        string 指定日, 
                        string お客様番号, 
                        string 輸送記事１, 
                        string 輸送記事２, 
                        string 品名記事１, 
                        string 品名記事２, 
                        string 品名記事３, 
                        string 品名記事４, 
                        string 品名記事５, 
                        string 品名記事６, 
                        int 印刷順, 
                        string 仕分ＣＤ, 
                        string 発店名, 
                        string 荷受人フォントサイズ拡大FLG, 
                        string 荷受人郵便番号, 
                        string 荷送人郵便番号, 
                        string 王子運送FLG, 
                        string 重量入力制御, 
                        string 着店名) {
                table送り状Row rowtable送り状Row = ((table送り状Row)(this.NewRow()));
                rowtable送り状Row.ItemArray = new object[] {
                        荷受人ＣＤ,
                        荷受人電話番号,
                        荷受人住所県,
                        荷受人住所市,
                        荷受人住所町,
                        荷受人住所１,
                        荷受人住所２,
                        荷受人住所３,
                        荷受人名前１,
                        荷受人名前２,
                        荷受人名前３,
                        出荷日年,
                        出荷日月,
                        出荷日日,
                        送り状番号,
                        バーコード,
                        着店ＣＤ,
                        発店ＣＤ,
                        荷送人電話番号,
                        荷送人住所１,
                        荷送人住所２,
                        荷送人住所３,
                        荷送人名前１,
                        荷送人名前２,
                        担当者,
                        個数,
                        連番,
                        重量,
                        保険料,
                        指定日,
                        お客様番号,
                        輸送記事１,
                        輸送記事２,
                        品名記事１,
                        品名記事２,
                        品名記事３,
                        品名記事４,
                        品名記事５,
                        品名記事６,
                        印刷順,
                        仕分ＣＤ,
                        発店名,
                        荷受人フォントサイズ拡大FLG,
                        荷受人郵便番号,
                        荷送人郵便番号,
                        王子運送FLG,
                        重量入力制御,
                        着店名};
                this.Rows.Add(rowtable送り状Row);
                return rowtable送り状Row;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                table送り状DataTable cln = ((table送り状DataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new table送り状DataTable();
            }
            
            internal void InitVars() {
                this.column荷受人ＣＤ = this.Columns["荷受人ＣＤ"];
                this.column荷受人電話番号 = this.Columns["荷受人電話番号"];
                this.column荷受人住所県 = this.Columns["荷受人住所県"];
                this.column荷受人住所市 = this.Columns["荷受人住所市"];
                this.column荷受人住所町 = this.Columns["荷受人住所町"];
                this.column荷受人住所１ = this.Columns["荷受人住所１"];
                this.column荷受人住所２ = this.Columns["荷受人住所２"];
                this.column荷受人住所３ = this.Columns["荷受人住所３"];
                this.column荷受人名前１ = this.Columns["荷受人名前１"];
                this.column荷受人名前２ = this.Columns["荷受人名前２"];
                this.column荷受人名前３ = this.Columns["荷受人名前３"];
                this.column出荷日年 = this.Columns["出荷日年"];
                this.column出荷日月 = this.Columns["出荷日月"];
                this.column出荷日日 = this.Columns["出荷日日"];
                this.column送り状番号 = this.Columns["送り状番号"];
                this.columnバーコード = this.Columns["バーコード"];
                this.column着店ＣＤ = this.Columns["着店ＣＤ"];
                this.column発店ＣＤ = this.Columns["発店ＣＤ"];
                this.column荷送人電話番号 = this.Columns["荷送人電話番号"];
                this.column荷送人住所１ = this.Columns["荷送人住所１"];
                this.column荷送人住所２ = this.Columns["荷送人住所２"];
                this.column荷送人住所３ = this.Columns["荷送人住所３"];
                this.column荷送人名前１ = this.Columns["荷送人名前１"];
                this.column荷送人名前２ = this.Columns["荷送人名前２"];
                this.column担当者 = this.Columns["担当者"];
                this.column個数 = this.Columns["個数"];
                this.column連番 = this.Columns["連番"];
                this.column重量 = this.Columns["重量"];
                this.column保険料 = this.Columns["保険料"];
                this.column指定日 = this.Columns["指定日"];
                this.columnお客様番号 = this.Columns["お客様番号"];
                this.column輸送記事１ = this.Columns["輸送記事１"];
                this.column輸送記事２ = this.Columns["輸送記事２"];
                this.column品名記事１ = this.Columns["品名記事１"];
                this.column品名記事２ = this.Columns["品名記事２"];
                this.column品名記事３ = this.Columns["品名記事３"];
                this.column品名記事４ = this.Columns["品名記事４"];
                this.column品名記事５ = this.Columns["品名記事５"];
                this.column品名記事６ = this.Columns["品名記事６"];
                this.column印刷順 = this.Columns["印刷順"];
                this.column仕分ＣＤ = this.Columns["仕分ＣＤ"];
                this.column発店名 = this.Columns["発店名"];
                this.column荷受人フォントサイズ拡大FLG = this.Columns["荷受人フォントサイズ拡大FLG"];
                this.column荷受人郵便番号 = this.Columns["荷受人郵便番号"];
                this.column荷送人郵便番号 = this.Columns["荷送人郵便番号"];
                this.column王子運送FLG = this.Columns["王子運送FLG"];
                this.column重量入力制御 = this.Columns["重量入力制御"];
                this.column着店名 = this.Columns["着店名"];
            }
            
            private void InitClass() {
                this.column荷受人ＣＤ = new DataColumn("荷受人ＣＤ", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷受人ＣＤ);
                this.column荷受人電話番号 = new DataColumn("荷受人電話番号", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷受人電話番号);
                this.column荷受人住所県 = new DataColumn("荷受人住所県", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷受人住所県);
                this.column荷受人住所市 = new DataColumn("荷受人住所市", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷受人住所市);
                this.column荷受人住所町 = new DataColumn("荷受人住所町", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷受人住所町);
                this.column荷受人住所１ = new DataColumn("荷受人住所１", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷受人住所１);
                this.column荷受人住所２ = new DataColumn("荷受人住所２", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷受人住所２);
                this.column荷受人住所３ = new DataColumn("荷受人住所３", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷受人住所３);
                this.column荷受人名前１ = new DataColumn("荷受人名前１", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷受人名前１);
                this.column荷受人名前２ = new DataColumn("荷受人名前２", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷受人名前２);
                this.column荷受人名前３ = new DataColumn("荷受人名前３", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷受人名前３);
                this.column出荷日年 = new DataColumn("出荷日年", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column出荷日年);
                this.column出荷日月 = new DataColumn("出荷日月", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column出荷日月);
                this.column出荷日日 = new DataColumn("出荷日日", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column出荷日日);
                this.column送り状番号 = new DataColumn("送り状番号", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column送り状番号);
                this.columnバーコード = new DataColumn("バーコード", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnバーコード);
                this.column着店ＣＤ = new DataColumn("着店ＣＤ", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column着店ＣＤ);
                this.column発店ＣＤ = new DataColumn("発店ＣＤ", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column発店ＣＤ);
                this.column荷送人電話番号 = new DataColumn("荷送人電話番号", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷送人電話番号);
                this.column荷送人住所１ = new DataColumn("荷送人住所１", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷送人住所１);
                this.column荷送人住所２ = new DataColumn("荷送人住所２", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷送人住所２);
                this.column荷送人住所３ = new DataColumn("荷送人住所３", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷送人住所３);
                this.column荷送人名前１ = new DataColumn("荷送人名前１", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷送人名前１);
                this.column荷送人名前２ = new DataColumn("荷送人名前２", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷送人名前２);
                this.column担当者 = new DataColumn("担当者", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column担当者);
                this.column個数 = new DataColumn("個数", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column個数);
                this.column連番 = new DataColumn("連番", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column連番);
                this.column重量 = new DataColumn("重量", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column重量);
                this.column保険料 = new DataColumn("保険料", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column保険料);
                this.column指定日 = new DataColumn("指定日", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column指定日);
                this.columnお客様番号 = new DataColumn("お客様番号", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnお客様番号);
                this.column輸送記事１ = new DataColumn("輸送記事１", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column輸送記事１);
                this.column輸送記事２ = new DataColumn("輸送記事２", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column輸送記事２);
                this.column品名記事１ = new DataColumn("品名記事１", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column品名記事１);
                this.column品名記事２ = new DataColumn("品名記事２", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column品名記事２);
                this.column品名記事３ = new DataColumn("品名記事３", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column品名記事３);
                this.column品名記事４ = new DataColumn("品名記事４", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column品名記事４);
                this.column品名記事５ = new DataColumn("品名記事５", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column品名記事５);
                this.column品名記事６ = new DataColumn("品名記事６", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column品名記事６);
                this.column印刷順 = new DataColumn("印刷順", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column印刷順);
                this.column仕分ＣＤ = new DataColumn("仕分ＣＤ", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column仕分ＣＤ);
                this.column発店名 = new DataColumn("発店名", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column発店名);
                this.column荷受人フォントサイズ拡大FLG = new DataColumn("荷受人フォントサイズ拡大FLG", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷受人フォントサイズ拡大FLG);
                this.column荷受人郵便番号 = new DataColumn("荷受人郵便番号", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷受人郵便番号);
                this.column荷送人郵便番号 = new DataColumn("荷送人郵便番号", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column荷送人郵便番号);
                this.column王子運送FLG = new DataColumn("王子運送FLG", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column王子運送FLG);
                this.column重量入力制御 = new DataColumn("重量入力制御", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column重量入力制御);
                this.column着店名 = new DataColumn("着店名", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column着店名);
                this.column荷送人名前２.AllowDBNull = false;
            }
            
            public table送り状Row Newtable送り状Row() {
                return ((table送り状Row)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new table送り状Row(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(table送り状Row);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.table送り状RowChanged != null)) {
                    this.table送り状RowChanged(this, new table送り状RowChangeEvent(((table送り状Row)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.table送り状RowChanging != null)) {
                    this.table送り状RowChanging(this, new table送り状RowChangeEvent(((table送り状Row)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.table送り状RowDeleted != null)) {
                    this.table送り状RowDeleted(this, new table送り状RowChangeEvent(((table送り状Row)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.table送り状RowDeleting != null)) {
                    this.table送り状RowDeleting(this, new table送り状RowChangeEvent(((table送り状Row)(e.Row)), e.Action));
                }
            }
            
            public void Removetable送り状Row(table送り状Row row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class table送り状Row : DataRow {
            
            private table送り状DataTable tabletable送り状;
            
            internal table送り状Row(DataRowBuilder rb) : 
                    base(rb) {
                this.tabletable送り状 = ((table送り状DataTable)(this.Table));
            }
            
            public string 荷受人ＣＤ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.荷受人ＣＤColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.荷受人ＣＤColumn] = value;
                }
            }
            
            public string 荷受人電話番号 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.荷受人電話番号Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.荷受人電話番号Column] = value;
                }
            }
            
            public string 荷受人住所県 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.荷受人住所県Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.荷受人住所県Column] = value;
                }
            }
            
            public string 荷受人住所市 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.荷受人住所市Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.荷受人住所市Column] = value;
                }
            }
            
            public string 荷受人住所町 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.荷受人住所町Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.荷受人住所町Column] = value;
                }
            }
            
            public string 荷受人住所１ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.荷受人住所１Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.荷受人住所１Column] = value;
                }
            }
            
            public string 荷受人住所２ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.荷受人住所２Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.荷受人住所２Column] = value;
                }
            }
            
            public string 荷受人住所３ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.荷受人住所３Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.荷受人住所３Column] = value;
                }
            }
            
            public string 荷受人名前１ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.荷受人名前１Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.荷受人名前１Column] = value;
                }
            }
            
            public string 荷受人名前２ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.荷受人名前２Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.荷受人名前２Column] = value;
                }
            }
            
            public string 荷受人名前３ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.荷受人名前３Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.荷受人名前３Column] = value;
                }
            }
            
            public string 出荷日年 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.出荷日年Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.出荷日年Column] = value;
                }
            }
            
            public string 出荷日月 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.出荷日月Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.出荷日月Column] = value;
                }
            }
            
            public string 出荷日日 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.出荷日日Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.出荷日日Column] = value;
                }
            }
            
            public string 送り状番号 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.送り状番号Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.送り状番号Column] = value;
                }
            }
            
            public string バーコード {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.バーコードColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.バーコードColumn] = value;
                }
            }
            
            public string 着店ＣＤ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.着店ＣＤColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.着店ＣＤColumn] = value;
                }
            }
            
            public string 発店ＣＤ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.発店ＣＤColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.発店ＣＤColumn] = value;
                }
            }
            
            public string 荷送人電話番号 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.荷送人電話番号Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.荷送人電話番号Column] = value;
                }
            }
            
            public string 荷送人住所１ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.荷送人住所１Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.荷送人住所１Column] = value;
                }
            }
            
            public string 荷送人住所２ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.荷送人住所２Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.荷送人住所２Column] = value;
                }
            }
            
            public string 荷送人住所３ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.荷送人住所３Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.荷送人住所３Column] = value;
                }
            }
            
            public string 荷送人名前１ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.荷送人名前１Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.荷送人名前１Column] = value;
                }
            }
            
            public string 荷送人名前２ {
                get {
                    return ((string)(this[this.tabletable送り状.荷送人名前２Column]));
                }
                set {
                    this[this.tabletable送り状.荷送人名前２Column] = value;
                }
            }
            
            public string 担当者 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.担当者Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.担当者Column] = value;
                }
            }
            
            public string 個数 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.個数Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.個数Column] = value;
                }
            }
            
            public string 連番 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.連番Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.連番Column] = value;
                }
            }
            
            public string 重量 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.重量Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.重量Column] = value;
                }
            }
            
            public string 保険料 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.保険料Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.保険料Column] = value;
                }
            }
            
            public string 指定日 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.指定日Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.指定日Column] = value;
                }
            }
            
            public string お客様番号 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.お客様番号Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.お客様番号Column] = value;
                }
            }
            
            public string 輸送記事１ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.輸送記事１Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.輸送記事１Column] = value;
                }
            }
            
            public string 輸送記事２ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.輸送記事２Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.輸送記事２Column] = value;
                }
            }
            
            public string 品名記事１ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.品名記事１Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.品名記事１Column] = value;
                }
            }
            
            public string 品名記事２ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.品名記事２Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.品名記事２Column] = value;
                }
            }
            
            public string 品名記事３ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.品名記事３Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.品名記事３Column] = value;
                }
            }
            
            public string 品名記事４ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.品名記事４Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.品名記事４Column] = value;
                }
            }
            
            public string 品名記事５ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.品名記事５Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.品名記事５Column] = value;
                }
            }
            
            public string 品名記事６ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.品名記事６Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.品名記事６Column] = value;
                }
            }
            
            public int 印刷順 {
                get {
                    try {
                        return ((int)(this[this.tabletable送り状.印刷順Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.印刷順Column] = value;
                }
            }
            
            public string 仕分ＣＤ {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.仕分ＣＤColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.仕分ＣＤColumn] = value;
                }
            }
            
            public string 発店名 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.発店名Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.発店名Column] = value;
                }
            }
            
            public string 荷受人フォントサイズ拡大FLG {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.荷受人フォントサイズ拡大FLGColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.荷受人フォントサイズ拡大FLGColumn] = value;
                }
            }
            
            public string 荷受人郵便番号 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.荷受人郵便番号Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.荷受人郵便番号Column] = value;
                }
            }
            
            public string 荷送人郵便番号 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.荷送人郵便番号Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.荷送人郵便番号Column] = value;
                }
            }
            
            public string 王子運送FLG {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.王子運送FLGColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.王子運送FLGColumn] = value;
                }
            }
            
            public string 重量入力制御 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.重量入力制御Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.重量入力制御Column] = value;
                }
            }
            
            public string 着店名 {
                get {
                    try {
                        return ((string)(this[this.tabletable送り状.着店名Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletable送り状.着店名Column] = value;
                }
            }
            
            public bool Is荷受人ＣＤNull() {
                return this.IsNull(this.tabletable送り状.荷受人ＣＤColumn);
            }
            
            public void Set荷受人ＣＤNull() {
                this[this.tabletable送り状.荷受人ＣＤColumn] = System.Convert.DBNull;
            }
            
            public bool Is荷受人電話番号Null() {
                return this.IsNull(this.tabletable送り状.荷受人電話番号Column);
            }
            
            public void Set荷受人電話番号Null() {
                this[this.tabletable送り状.荷受人電話番号Column] = System.Convert.DBNull;
            }
            
            public bool Is荷受人住所県Null() {
                return this.IsNull(this.tabletable送り状.荷受人住所県Column);
            }
            
            public void Set荷受人住所県Null() {
                this[this.tabletable送り状.荷受人住所県Column] = System.Convert.DBNull;
            }
            
            public bool Is荷受人住所市Null() {
                return this.IsNull(this.tabletable送り状.荷受人住所市Column);
            }
            
            public void Set荷受人住所市Null() {
                this[this.tabletable送り状.荷受人住所市Column] = System.Convert.DBNull;
            }
            
            public bool Is荷受人住所町Null() {
                return this.IsNull(this.tabletable送り状.荷受人住所町Column);
            }
            
            public void Set荷受人住所町Null() {
                this[this.tabletable送り状.荷受人住所町Column] = System.Convert.DBNull;
            }
            
            public bool Is荷受人住所１Null() {
                return this.IsNull(this.tabletable送り状.荷受人住所１Column);
            }
            
            public void Set荷受人住所１Null() {
                this[this.tabletable送り状.荷受人住所１Column] = System.Convert.DBNull;
            }
            
            public bool Is荷受人住所２Null() {
                return this.IsNull(this.tabletable送り状.荷受人住所２Column);
            }
            
            public void Set荷受人住所２Null() {
                this[this.tabletable送り状.荷受人住所２Column] = System.Convert.DBNull;
            }
            
            public bool Is荷受人住所３Null() {
                return this.IsNull(this.tabletable送り状.荷受人住所３Column);
            }
            
            public void Set荷受人住所３Null() {
                this[this.tabletable送り状.荷受人住所３Column] = System.Convert.DBNull;
            }
            
            public bool Is荷受人名前１Null() {
                return this.IsNull(this.tabletable送り状.荷受人名前１Column);
            }
            
            public void Set荷受人名前１Null() {
                this[this.tabletable送り状.荷受人名前１Column] = System.Convert.DBNull;
            }
            
            public bool Is荷受人名前２Null() {
                return this.IsNull(this.tabletable送り状.荷受人名前２Column);
            }
            
            public void Set荷受人名前２Null() {
                this[this.tabletable送り状.荷受人名前２Column] = System.Convert.DBNull;
            }
            
            public bool Is荷受人名前３Null() {
                return this.IsNull(this.tabletable送り状.荷受人名前３Column);
            }
            
            public void Set荷受人名前３Null() {
                this[this.tabletable送り状.荷受人名前３Column] = System.Convert.DBNull;
            }
            
            public bool Is出荷日年Null() {
                return this.IsNull(this.tabletable送り状.出荷日年Column);
            }
            
            public void Set出荷日年Null() {
                this[this.tabletable送り状.出荷日年Column] = System.Convert.DBNull;
            }
            
            public bool Is出荷日月Null() {
                return this.IsNull(this.tabletable送り状.出荷日月Column);
            }
            
            public void Set出荷日月Null() {
                this[this.tabletable送り状.出荷日月Column] = System.Convert.DBNull;
            }
            
            public bool Is出荷日日Null() {
                return this.IsNull(this.tabletable送り状.出荷日日Column);
            }
            
            public void Set出荷日日Null() {
                this[this.tabletable送り状.出荷日日Column] = System.Convert.DBNull;
            }
            
            public bool Is送り状番号Null() {
                return this.IsNull(this.tabletable送り状.送り状番号Column);
            }
            
            public void Set送り状番号Null() {
                this[this.tabletable送り状.送り状番号Column] = System.Convert.DBNull;
            }
            
            public bool IsバーコードNull() {
                return this.IsNull(this.tabletable送り状.バーコードColumn);
            }
            
            public void SetバーコードNull() {
                this[this.tabletable送り状.バーコードColumn] = System.Convert.DBNull;
            }
            
            public bool Is着店ＣＤNull() {
                return this.IsNull(this.tabletable送り状.着店ＣＤColumn);
            }
            
            public void Set着店ＣＤNull() {
                this[this.tabletable送り状.着店ＣＤColumn] = System.Convert.DBNull;
            }
            
            public bool Is発店ＣＤNull() {
                return this.IsNull(this.tabletable送り状.発店ＣＤColumn);
            }
            
            public void Set発店ＣＤNull() {
                this[this.tabletable送り状.発店ＣＤColumn] = System.Convert.DBNull;
            }
            
            public bool Is荷送人電話番号Null() {
                return this.IsNull(this.tabletable送り状.荷送人電話番号Column);
            }
            
            public void Set荷送人電話番号Null() {
                this[this.tabletable送り状.荷送人電話番号Column] = System.Convert.DBNull;
            }
            
            public bool Is荷送人住所１Null() {
                return this.IsNull(this.tabletable送り状.荷送人住所１Column);
            }
            
            public void Set荷送人住所１Null() {
                this[this.tabletable送り状.荷送人住所１Column] = System.Convert.DBNull;
            }
            
            public bool Is荷送人住所２Null() {
                return this.IsNull(this.tabletable送り状.荷送人住所２Column);
            }
            
            public void Set荷送人住所２Null() {
                this[this.tabletable送り状.荷送人住所２Column] = System.Convert.DBNull;
            }
            
            public bool Is荷送人住所３Null() {
                return this.IsNull(this.tabletable送り状.荷送人住所３Column);
            }
            
            public void Set荷送人住所３Null() {
                this[this.tabletable送り状.荷送人住所３Column] = System.Convert.DBNull;
            }
            
            public bool Is荷送人名前１Null() {
                return this.IsNull(this.tabletable送り状.荷送人名前１Column);
            }
            
            public void Set荷送人名前１Null() {
                this[this.tabletable送り状.荷送人名前１Column] = System.Convert.DBNull;
            }
            
            public bool Is担当者Null() {
                return this.IsNull(this.tabletable送り状.担当者Column);
            }
            
            public void Set担当者Null() {
                this[this.tabletable送り状.担当者Column] = System.Convert.DBNull;
            }
            
            public bool Is個数Null() {
                return this.IsNull(this.tabletable送り状.個数Column);
            }
            
            public void Set個数Null() {
                this[this.tabletable送り状.個数Column] = System.Convert.DBNull;
            }
            
            public bool Is連番Null() {
                return this.IsNull(this.tabletable送り状.連番Column);
            }
            
            public void Set連番Null() {
                this[this.tabletable送り状.連番Column] = System.Convert.DBNull;
            }
            
            public bool Is重量Null() {
                return this.IsNull(this.tabletable送り状.重量Column);
            }
            
            public void Set重量Null() {
                this[this.tabletable送り状.重量Column] = System.Convert.DBNull;
            }
            
            public bool Is保険料Null() {
                return this.IsNull(this.tabletable送り状.保険料Column);
            }
            
            public void Set保険料Null() {
                this[this.tabletable送り状.保険料Column] = System.Convert.DBNull;
            }
            
            public bool Is指定日Null() {
                return this.IsNull(this.tabletable送り状.指定日Column);
            }
            
            public void Set指定日Null() {
                this[this.tabletable送り状.指定日Column] = System.Convert.DBNull;
            }
            
            public bool Isお客様番号Null() {
                return this.IsNull(this.tabletable送り状.お客様番号Column);
            }
            
            public void Setお客様番号Null() {
                this[this.tabletable送り状.お客様番号Column] = System.Convert.DBNull;
            }
            
            public bool Is輸送記事１Null() {
                return this.IsNull(this.tabletable送り状.輸送記事１Column);
            }
            
            public void Set輸送記事１Null() {
                this[this.tabletable送り状.輸送記事１Column] = System.Convert.DBNull;
            }
            
            public bool Is輸送記事２Null() {
                return this.IsNull(this.tabletable送り状.輸送記事２Column);
            }
            
            public void Set輸送記事２Null() {
                this[this.tabletable送り状.輸送記事２Column] = System.Convert.DBNull;
            }
            
            public bool Is品名記事１Null() {
                return this.IsNull(this.tabletable送り状.品名記事１Column);
            }
            
            public void Set品名記事１Null() {
                this[this.tabletable送り状.品名記事１Column] = System.Convert.DBNull;
            }
            
            public bool Is品名記事２Null() {
                return this.IsNull(this.tabletable送り状.品名記事２Column);
            }
            
            public void Set品名記事２Null() {
                this[this.tabletable送り状.品名記事２Column] = System.Convert.DBNull;
            }
            
            public bool Is品名記事３Null() {
                return this.IsNull(this.tabletable送り状.品名記事３Column);
            }
            
            public void Set品名記事３Null() {
                this[this.tabletable送り状.品名記事３Column] = System.Convert.DBNull;
            }
            
            public bool Is品名記事４Null() {
                return this.IsNull(this.tabletable送り状.品名記事４Column);
            }
            
            public void Set品名記事４Null() {
                this[this.tabletable送り状.品名記事４Column] = System.Convert.DBNull;
            }
            
            public bool Is品名記事５Null() {
                return this.IsNull(this.tabletable送り状.品名記事５Column);
            }
            
            public void Set品名記事５Null() {
                this[this.tabletable送り状.品名記事５Column] = System.Convert.DBNull;
            }
            
            public bool Is品名記事６Null() {
                return this.IsNull(this.tabletable送り状.品名記事６Column);
            }
            
            public void Set品名記事６Null() {
                this[this.tabletable送り状.品名記事６Column] = System.Convert.DBNull;
            }
            
            public bool Is印刷順Null() {
                return this.IsNull(this.tabletable送り状.印刷順Column);
            }
            
            public void Set印刷順Null() {
                this[this.tabletable送り状.印刷順Column] = System.Convert.DBNull;
            }
            
            public bool Is仕分ＣＤNull() {
                return this.IsNull(this.tabletable送り状.仕分ＣＤColumn);
            }
            
            public void Set仕分ＣＤNull() {
                this[this.tabletable送り状.仕分ＣＤColumn] = System.Convert.DBNull;
            }
            
            public bool Is発店名Null() {
                return this.IsNull(this.tabletable送り状.発店名Column);
            }
            
            public void Set発店名Null() {
                this[this.tabletable送り状.発店名Column] = System.Convert.DBNull;
            }
            
            public bool Is荷受人フォントサイズ拡大FLGNull() {
                return this.IsNull(this.tabletable送り状.荷受人フォントサイズ拡大FLGColumn);
            }
            
            public void Set荷受人フォントサイズ拡大FLGNull() {
                this[this.tabletable送り状.荷受人フォントサイズ拡大FLGColumn] = System.Convert.DBNull;
            }
            
            public bool Is荷受人郵便番号Null() {
                return this.IsNull(this.tabletable送り状.荷受人郵便番号Column);
            }
            
            public void Set荷受人郵便番号Null() {
                this[this.tabletable送り状.荷受人郵便番号Column] = System.Convert.DBNull;
            }
            
            public bool Is荷送人郵便番号Null() {
                return this.IsNull(this.tabletable送り状.荷送人郵便番号Column);
            }
            
            public void Set荷送人郵便番号Null() {
                this[this.tabletable送り状.荷送人郵便番号Column] = System.Convert.DBNull;
            }
            
            public bool Is王子運送FLGNull() {
                return this.IsNull(this.tabletable送り状.王子運送FLGColumn);
            }
            
            public void Set王子運送FLGNull() {
                this[this.tabletable送り状.王子運送FLGColumn] = System.Convert.DBNull;
            }
            
            public bool Is重量入力制御Null() {
                return this.IsNull(this.tabletable送り状.重量入力制御Column);
            }
            
            public void Set重量入力制御Null() {
                this[this.tabletable送り状.重量入力制御Column] = System.Convert.DBNull;
            }
            
            public bool Is着店名Null() {
                return this.IsNull(this.tabletable送り状.着店名Column);
            }
            
            public void Set着店名Null() {
                this[this.tabletable送り状.着店名Column] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class table送り状RowChangeEvent : EventArgs {
            
            private table送り状Row eventRow;
            
            private DataRowAction eventAction;
            
            public table送り状RowChangeEvent(table送り状Row row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public table送り状Row Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
